name: mai2_revive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  oktoast: ^3.4.0
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
